package com.gether.bigdata.dao.dataobject;

import java.io.Serializable;
import java.util.Date;

public class ODevice implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_device.did
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    private Integer did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_device.deviceid
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    private String deviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_device.status
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_device.registertime
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    private Date registertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_device.unregistertime
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    private Date unregistertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_device.comment
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_device.devicename
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    private String devicename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_device.modelid
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    private String modelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_device.cloudid
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    private Integer cloudid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_device.uid
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_device.share
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    private String share;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_device.ip
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_device.region
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_device.ratestatus
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    private Integer ratestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column o_device.productkey
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    private String productkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table o_device
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_device.did
     *
     * @return the value of o_device.did
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_device.did
     *
     * @param did the value for o_device.did
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_device.deviceid
     *
     * @return the value of o_device.deviceid
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_device.deviceid
     *
     * @param deviceid the value for o_device.deviceid
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_device.status
     *
     * @return the value of o_device.status
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_device.status
     *
     * @param status the value for o_device.status
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_device.registertime
     *
     * @return the value of o_device.registertime
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_device.registertime
     *
     * @param registertime the value for o_device.registertime
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_device.unregistertime
     *
     * @return the value of o_device.unregistertime
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public Date getUnregistertime() {
        return unregistertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_device.unregistertime
     *
     * @param unregistertime the value for o_device.unregistertime
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public void setUnregistertime(Date unregistertime) {
        this.unregistertime = unregistertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_device.comment
     *
     * @return the value of o_device.comment
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_device.comment
     *
     * @param comment the value for o_device.comment
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_device.devicename
     *
     * @return the value of o_device.devicename
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public String getDevicename() {
        return devicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_device.devicename
     *
     * @param devicename the value for o_device.devicename
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public void setDevicename(String devicename) {
        this.devicename = devicename == null ? null : devicename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_device.modelid
     *
     * @return the value of o_device.modelid
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public String getModelid() {
        return modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_device.modelid
     *
     * @param modelid the value for o_device.modelid
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public void setModelid(String modelid) {
        this.modelid = modelid == null ? null : modelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_device.cloudid
     *
     * @return the value of o_device.cloudid
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public Integer getCloudid() {
        return cloudid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_device.cloudid
     *
     * @param cloudid the value for o_device.cloudid
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public void setCloudid(Integer cloudid) {
        this.cloudid = cloudid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_device.uid
     *
     * @return the value of o_device.uid
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_device.uid
     *
     * @param uid the value for o_device.uid
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_device.share
     *
     * @return the value of o_device.share
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public String getShare() {
        return share;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_device.share
     *
     * @param share the value for o_device.share
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public void setShare(String share) {
        this.share = share == null ? null : share.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_device.ip
     *
     * @return the value of o_device.ip
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_device.ip
     *
     * @param ip the value for o_device.ip
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_device.region
     *
     * @return the value of o_device.region
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_device.region
     *
     * @param region the value for o_device.region
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_device.ratestatus
     *
     * @return the value of o_device.ratestatus
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public Integer getRatestatus() {
        return ratestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_device.ratestatus
     *
     * @param ratestatus the value for o_device.ratestatus
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public void setRatestatus(Integer ratestatus) {
        this.ratestatus = ratestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column o_device.productkey
     *
     * @return the value of o_device.productkey
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public String getProductkey() {
        return productkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column o_device.productkey
     *
     * @param productkey the value for o_device.productkey
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    public void setProductkey(String productkey) {
        this.productkey = productkey == null ? null : productkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_device
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ODevice other = (ODevice) that;
        return (this.getDid() == null ? other.getDid() == null : this.getDid().equals(other.getDid()))
            && (this.getDeviceid() == null ? other.getDeviceid() == null : this.getDeviceid().equals(other.getDeviceid()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getRegistertime() == null ? other.getRegistertime() == null : this.getRegistertime().equals(other.getRegistertime()))
            && (this.getUnregistertime() == null ? other.getUnregistertime() == null : this.getUnregistertime().equals(other.getUnregistertime()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (this.getDevicename() == null ? other.getDevicename() == null : this.getDevicename().equals(other.getDevicename()))
            && (this.getModelid() == null ? other.getModelid() == null : this.getModelid().equals(other.getModelid()))
            && (this.getCloudid() == null ? other.getCloudid() == null : this.getCloudid().equals(other.getCloudid()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getShare() == null ? other.getShare() == null : this.getShare().equals(other.getShare()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getRegion() == null ? other.getRegion() == null : this.getRegion().equals(other.getRegion()))
            && (this.getRatestatus() == null ? other.getRatestatus() == null : this.getRatestatus().equals(other.getRatestatus()))
            && (this.getProductkey() == null ? other.getProductkey() == null : this.getProductkey().equals(other.getProductkey()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_device
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDid() == null) ? 0 : getDid().hashCode());
        result = prime * result + ((getDeviceid() == null) ? 0 : getDeviceid().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRegistertime() == null) ? 0 : getRegistertime().hashCode());
        result = prime * result + ((getUnregistertime() == null) ? 0 : getUnregistertime().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getDevicename() == null) ? 0 : getDevicename().hashCode());
        result = prime * result + ((getModelid() == null) ? 0 : getModelid().hashCode());
        result = prime * result + ((getCloudid() == null) ? 0 : getCloudid().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getShare() == null) ? 0 : getShare().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getRegion() == null) ? 0 : getRegion().hashCode());
        result = prime * result + ((getRatestatus() == null) ? 0 : getRatestatus().hashCode());
        result = prime * result + ((getProductkey() == null) ? 0 : getProductkey().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_device
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", did=").append(did);
        sb.append(", deviceid=").append(deviceid);
        sb.append(", status=").append(status);
        sb.append(", registertime=").append(registertime);
        sb.append(", unregistertime=").append(unregistertime);
        sb.append(", comment=").append(comment);
        sb.append(", devicename=").append(devicename);
        sb.append(", modelid=").append(modelid);
        sb.append(", cloudid=").append(cloudid);
        sb.append(", uid=").append(uid);
        sb.append(", share=").append(share);
        sb.append(", ip=").append(ip);
        sb.append(", region=").append(region);
        sb.append(", ratestatus=").append(ratestatus);
        sb.append(", productkey=").append(productkey);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}