package com.gether.bigdata.dao.mapper;

import com.gether.bigdata.dao.dataobject.ODevice;
import com.gether.bigdata.dao.dataobject.ODeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ODeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_device
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    long countByExample(ODeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_device
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    int deleteByExample(ODeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_device
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    int deleteByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_device
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    int insert(ODevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_device
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    int insertSelective(ODevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_device
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    List<ODevice> selectByExample(ODeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_device
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    ODevice selectByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_device
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") ODevice record, @Param("example") ODeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_device
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    int updateByExample(@Param("record") ODevice record, @Param("example") ODeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_device
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    int updateByPrimaryKeySelective(ODevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table o_device
     *
     * @mbg.generated Mon Jan 23 22:21:29 CST 2017
     */
    int updateByPrimaryKey(ODevice record);
}